import os
import re
import json
import pdfplumber
from huggingface_hub import InferenceClient

LLM_PROMPT = """
You are extracting database normalization answers.

STRICT RULES:
- Output ONLY valid JSON
- Do NOT include markdown, comments, or explanations
- Do NOT invent attributes, tables, or dependencies
- If information is missing, use empty lists []
- Attribute names must be lowercase
- Use '->' for functional dependencies
- Follow the JSON format EXACTLY

REQUIRED JSON FORMAT:
{
  "attribute": [],
  "multivalued": [],
  "compositeattributes": [],
  "fds": [],
  "1nf": [],
  "2nf": [],
  "3nf": [],
  "final_tables": []
}

Database Schema Description:
<<<{text}>>>
"""

def extract_text(file_like, filename: str):
    """
    Extract text. We receive a Streamlit UploadedFile object.
    """
    text = ""
    if filename.lower().endswith('.pdf'):
        with pdfplumber.open(file_like) as pdf:
            for page in pdf.pages:
                extracted = page.extract_text()
                if extracted: text += extracted + "\\n"
    else:
        text = file_like.getvalue().decode("utf-8")
    return text.strip()

def preprocess(text: str) -> str:
    text = text.lower()
    text = text.replace("→", "->").replace("=>", "->").replace(":", "->")
    text = re.sub(r"\\s+", " ", text)
    fillers = ["the table is", "we have", "let us consider", "primary key is", "pk is"]
    for f in fillers:
        text = text.replace(f, "")
    return text.strip()

def extract_json_from_response(text):
    match = re.search(r"\\{.*\\}", text, re.DOTALL)
    if not match:
        raise ValueError(f"No JSON found in response")
    return match.group(0)

def llm_extract_schema(text, hf_token=None, is_student=False):
    if not hf_token:
        raise ValueError("Hugging Face API token is required.")
        
    client = InferenceClient(api_key=hf_token)
    clean_text = preprocess(text)
    
    prompt = LLM_PROMPT.format(text=clean_text)
    if is_student:
        prompt = prompt.replace("Database Schema Description:", "Student Answer:")
        
    messages = [{"role": "user", "content": prompt}]
    
    response = client.chat.completions.create(
        model="Qwen/Qwen2.5-72B-Instruct", 
        messages=messages, 
        max_tokens=4096,
        temperature=0.0
    )
    
    raw_response = response.choices[0].message.content
    try:
        return json.loads(extract_json_from_response(raw_response))
    except Exception as e:
        print(f"Extraction Error: {e}")
        print(f"Raw Output: {raw_response}")
        return None

def generate_nlp_feedback(raw_feedback, student_name, score, max_score, hf_token=None):
    if not hf_token:
        return raw_feedback
        
    client = InferenceClient(api_key=hf_token)
    
    prompt = f"""You are an encouraging and helpful database systems teaching assistant grading a student's database normalization assignment.
The student's name is {student_name}.
They scored {score:.1f} out of {max_score:.1f}.
Here is the raw technical feedback generated by the automated grader:
"{raw_feedback}"

Please rewrite this feedback into a single, cohesive, engaging, natural-sounding paragraph addressed to the student. 
Be constructive, mention what they did right, and clearly explain what they missed based only on the raw feedback. 
Do not invent any new errors, and do not invent praise not supported by the raw feedback. Keep it concise and friendly.
"""
    messages = [{"role": "user", "content": prompt}]
    
    try:
        response = client.chat.completions.create(
            model="Qwen/Qwen2.5-72B-Instruct", 
            messages=messages, 
            max_tokens=500,
            temperature=0.3
        )
        return response.choices[0].message.content.strip()
    except Exception as e:
        print(f"Feedback Generation Error: {e}")
        return raw_feedback

def generate_class_summary(df_results, hf_token=None):
    if not hf_token or "Score" not in df_results.columns or df_results.empty:
        return "Insufficient data to generate an AI class performance summary."
        
    client = InferenceClient(api_key=hf_token)
    
    avg_score = df_results["Score"].mean()
    highest_score = df_results["Score"].max()
    lowest_score = df_results["Score"].min()
    
    sample_feedbacks = df_results['Feedback'].head(30).tolist()
    
    prompt = f"""You are a database systems instructor analyzing the results of a database normalization assignment.
The class average score was {avg_score:.1f}%. The highest score was {highest_score:.1f}% and the lowest was {lowest_score:.1f}%.

Here are some sample individual feedback notes given to the students:
{sample_feedbacks}

Based on this data, provide a professional, brief, and constructive summary of the overall class performance directed to the teacher. 
Identify any common mistakes or concepts the students struggled with in general, as well as areas they succeeded in.
Output a cohesive 1-2 paragraph overview. Do well to synthesize the individual feedbacks.
"""
    messages = [{"role": "user", "content": prompt}]
    
    try:
        response = client.chat.completions.create(
            model="Qwen/Qwen2.5-72B-Instruct", 
            messages=messages, 
            max_tokens=500,
            temperature=0.3
        )
        return response.choices[0].message.content.strip()
    except Exception as e:
        print(f"Class Summary Error: {e}")
        return "Failed to generate AI class summary."
